//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GenMAPPDBDL.rc
//
#define IDD_CDDBCOPY                    2000
#define IDD_PROGDLG                     2001
#define IDC_LIST2                       2002
#define IDC_DISKFREE                    2002
#define IDC_FREESPACELST                2002
#define IDC_LSTUPDATELOG                2002
#define IDC_SPEEDPROG                   2002
#define IDC_DBDLLIST                    2003
#define IDC_INETSTAT                    2005
#define IDC_GENEDIR                     2006
#define IDC_MAPPDIR                     2007
#define IDC_BUTTON3                     2008
#define IDC_GENEDIR2                    2008
#define IDC_REMOVEDB                    2008
#define IDC_GEXDIR                      2009
#define IDC_GDB                         2010
#define IDC_MAPP                        2011
#define IDC_EDIT3                       2012
#define IDC_OTRDIR                      2012
#define IDC_GEX                         2013
#define IDC_NEXTBTNMAN                  2014
#define IDC_OTR                         2014
#define IDC_CONNSPEED                   2015
#define IDC_PICGREENGRAD                2016
#define IDC_OVERALLPRG                  2017
#define IDB_BITMAP1                     2017
#define IDB_GENMAPPSPLASH               2017
#define IDC_SELCOUNT                    2018
#define IDD_GENBANKWARNING              2018
#define IDC_DLTIME                      2019
#define IDI_FOLDEROPEN                  2019
#define IDD_UPDATEDLG                   2019
#define IDC_TOTALDLSIZE                 2020
#define IDC_FILEINDL                    2020
#define IDI_FOLDERCLOSED                2020
#define IDC_FILETALLY                   2021
#define IDC_TOTALDLSIZE2                2021
#define IDC_FREESPACE                   2021
#define IDC_ABORT                       2022
#define IDC_PAUSE                       2023
#define IDI_REDLIGHT                    2023
#define IDC_CHKDONTSHOW                 2024
#define IDI_YELLOWLIGHT                 2024
#define IDI_GREENLIGHT                  2025
#define IDI_CHECKMARK                   2026
#define IDC_GENMAPPSPLASH               2027
#define IDI_RIGHTARROW                  2027
#define IDC_LIST1                       2028
#define IDC_DLQUEUE                     2028
#define IDI_REDX                        2028
#define IDC_LSTQUEUEDFILES              2028
#define IDI_ICON1                       2029
#define IDC_DBFOLDERTREE                2030
#define IDC_SHOWREADME                  2031
#define IDB_GENMAPPSPLASHSM             2031
#define IDC_READMETEXT                  2032
#define IDD_PROMPTFORUPDATE             2032
#define IDC_SELECTSUM                   2033
#define IDD_ADVOPTIONS                  2033
#define IDC_CONNSTATFRM                 2034
#define IDI_GENMAPP                     2034
#define IDC_STATUS_IND                  2035
#define IDD_FILEOVERWRITE               2035
#define IDC_BUTTON1                     2036
#define IDC_REFRESH                     2036
#define IDI_ICON2                       2036
#define IDI_DOT                         2036
#define IDC_TXTFREESPACE                2037
#define IDI_PAUSE                       2037
#define IDC_GRPOPTIONS                  2038
#define IDI_PAUSE1                      2038
#define IDI_BLANK                       2038
#define IDC_LBLUPDATELOG                2039
#define IDC_LABUPDATEPRG                2040
#define IDC_GRPUPDATEINFO               2041
#define IDC_LABUPDATESUM                2042
#define IDC_DATETIMEPICKER1             2043
#define IDC_BTNADVDLG                   2044
#define IDC_CHKDELCOMPFILES             2045
#define IDC_CHKOVRWRITEDATA             2046
#define IDC_BTNNOTOALL                  2047
#define IDC_LSTOVERWRITE                2048
#define IDC_BTNYESTOALL                 2049
#define IDC_LBLDLTOTALS                 2050
#define IDC_LBLDLSPEED                  2051
#define IDC_LBLREMAININGTIME            2052
#define IDC_DLSPEED                     2053
#define IDC_REMAININGTIME               2054
#define IDC_LBLFILENAME                 2055
#define IDC_LBLSERVERNAME               2056
#define IDC_FILENAME                    2057
#define IDC_SERVERNAME                  2058
#define IDC_LBLLOCATION                 2059
#define IDC_LOCATION                    2060
#define IDC_LBLBYTEDOWNLOADED           2061
#define IDC_BYTESDOWNLOADED             2062
#define IDC_LBLPERCENTCOMP              2063
#define IDC_PERCENTCOMP                 2064
#define IDC_LBLTRANSPORT                2065
#define IDC_TRANSPORT                   2066
#define IDC_LBLFILETYPE                 2067
#define IDC_FILETYPE                    2068
#define IDC_GRPDLSTATISTICS             2069
#define IDC_GRPCURRENTFILE              2070
#define IDC_DLFILE                      2071
#define IDC_TOTALBYTESDL                2072
#define IDC_LBLTOPMESSAGE               2073
#define IDC_GRPDLDESTINATIONS           2074
#define IDC_LBLGENEDB                   2075
#define IDC_LBLEXPDATA                  2076
#define IDC_LBLMAPPARC                  2077
#define IDC_LBLOTRINFO                  2078
#define IDC_LBLSELCOUNT                 2079
#define IDC_LBLESTDLTIME                2080
#define IDC_LBLDISKSPACE                2081
#define IDC_LBLFREESPACE                2082
#define IDC_LBLDLQUEUE                  2083
#define IDC_LBLDLSIZEVAL                2084
#define IDC_LBLDLSIZEKEY                2085
#define IDC_SPEEDTESTPROG               2086

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2037
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2087
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
